import { palette } from './palette.js';

export const REQUIRED_COLOR_KEYS = Object.freeze([
  'background',
  'surface',
  'surfaceMuted',
  'text',
  'textMuted',
  'textInverse',
  'border',
  'borderStrong',
  'primary',
  'primaryPressed',
  'onPrimary',
  'secondary',
  'secondaryPressed',
  'onSecondary',
  'danger',
  'dangerPressed',
  'onDanger',
  'warning',
  'success',
  'focus',
  'disabled',
]);

const createTheme = (mode, colors) =>
  Object.freeze({
    mode,
    colors: Object.freeze(colors),
  });

export const lightTheme = createTheme('light', {
  background: palette.neutral.white,
  surface: palette.neutral[50],
  surfaceMuted: palette.neutral[100],
  text: palette.neutral[900],
  textMuted: palette.neutral[600],
  textInverse: palette.neutral.white,
  border: palette.neutral[200],
  borderStrong: palette.neutral[400],
  primary: palette.primary[600],
  primaryPressed: palette.primary[800],
  onPrimary: palette.neutral.white,
  secondary: palette.field[600],
  secondaryPressed: palette.field[700],
  onSecondary: palette.neutral.white,
  danger: palette.danger[600],
  dangerPressed: palette.danger[700],
  onDanger: palette.neutral.white,
  warning: palette.warning[600],
  success: palette.field[600],
  focus: palette.primary[600],
  disabled: palette.neutral[400],
  selection: palette.primary[50],
  surfaceDanger: palette.danger[50],
  surfaceWarning: palette.warning[50],
  overlay: palette.neutral.blackTransparent,
  cameraChrome: palette.neutral[900],
});

export const darkTheme = createTheme('dark', {
  background: palette.neutral[950],
  surface: palette.dark[900],
  surfaceMuted: palette.dark[800],
  text: palette.neutral.lightText,
  textMuted: palette.neutral.lightMuted,
  textInverse: palette.neutral[950],
  border: palette.dark[700],
  borderStrong: palette.neutral[400],
  primary: palette.primary[400],
  primaryPressed: palette.primary[300],
  onPrimary: palette.neutral[950],
  secondary: palette.field[400],
  secondaryPressed: palette.field[500],
  onSecondary: palette.neutral[950],
  danger: palette.danger[400],
  dangerPressed: palette.danger[300],
  onDanger: palette.neutral[950],
  warning: palette.warning[400],
  success: palette.field[400],
  focus: palette.primary[400],
  disabled: palette.neutral[500],
  selection: palette.dark.selection,
  surfaceDanger: palette.dark.danger,
  surfaceWarning: palette.dark.warning,
  overlay: palette.neutral.blackTransparent,
  cameraChrome: palette.neutral.black,
});

export const resolveTheme = (colorScheme) => (colorScheme === 'dark' ? darkTheme : lightTheme);
