import { GATHER_ACTION_IDS, GATHER_CATALOG_ID, GATHER_COMPONENT_IDS } from './identifiers.js';

const SEGMENT_AND_MEASURE_OUTPUT_REVIEW = Object.freeze({
  title: 'Result accepted',
  description: 'Analysis is ready to include in this observation.',
  primaryActionLabel: 'Accept',
  secondaryActionLabel: 'Retake',
  sections: [
    { id: 'measurements', label: 'Measurements', order: 1 },
    { id: 'classification', label: 'Classification', order: 2 },
    { id: 'assets', label: 'Assets', order: 3 },
  ],
  fields: [
    {
      path: 'measurements.area.value',
      label: 'Area',
      format: 'quantity',
      unitPath: 'measurements.area.unit',
      section: 'measurements',
      decimals: 2,
      order: 1,
    },
    {
      path: 'measurements.perimeter.value',
      label: 'Perimeter',
      format: 'quantity',
      unitPath: 'measurements.perimeter.unit',
      section: 'measurements',
      decimals: 2,
      order: 2,
    },
    {
      path: 'measurements.boundingBox.width',
      label: 'Bounds width',
      format: 'quantity',
      unitPath: 'measurements.boundingBox.unit',
      section: 'measurements',
      decimals: 2,
      order: 3,
    },
    {
      path: 'measurements.boundingBox.height',
      label: 'Bounds height',
      format: 'quantity',
      unitPath: 'measurements.boundingBox.unit',
      section: 'measurements',
      decimals: 2,
      order: 4,
    },
    {
      path: 'measurements.sharpness.score',
      label: 'Sharpness',
      format: 'number',
      section: 'measurements',
      decimals: 2,
      order: 5,
    },
    {
      path: 'classification.ranked',
      label: 'Top labels',
      format: 'array',
      section: 'classification',
      order: 1,
      maxItems: 3,
      itemLabelPath: 'label',
      itemValuePath: 'score',
      itemValueFormat: 'percentage',
      itemValueScale: 'fraction',
      itemValueDecimals: 1,
      emptyText: 'Classification not run',
    },
    {
      path: 'segmentation.model.id',
      label: 'Segmentation model',
      format: 'string',
      section: 'assets',
      order: 1,
      emptyText: 'Segmentation completed',
    },
    {
      path: 'image',
      label: 'Captured image',
      format: 'asset',
      section: 'assets',
      order: 2,
      emptyText: 'Image summary unavailable',
    },
    {
      path: 'segmentation.mask',
      label: 'Mask asset',
      format: 'asset',
      section: 'assets',
      order: 3,
      emptyText: 'Mask summary unavailable',
    },
  ],
});

export const SEGMENT_AND_MEASURE_INSTRUMENT = Object.freeze({
  id: 'gather.segment-and-measure',
  revision: '0.1.0',
  catalogId: GATHER_CATALOG_ID,
  surfaceId: 'segment-and-measure',
  messages: Object.freeze([
    {
      version: 'v0.9',
      createSurface: {
        surfaceId: 'segment-and-measure',
        catalogId: GATHER_CATALOG_ID,
        sendDataModel: true,
      },
    },
    {
      version: 'v0.9',
      updateComponents: {
        surfaceId: 'segment-and-measure',
        components: [
          { id: 'root', component: 'Column', children: ['title', 'capture', 'review'] },
          { id: 'title', component: 'Text', text: 'Segment & Measure', variant: 'h2' },
          {
            id: 'capture',
            component: GATHER_COMPONENT_IDS.capture,
            phase: { path: '/gather/phase' },
            statePath: '/gather',
          },
          {
            id: 'review',
            component: GATHER_COMPONENT_IDS.maskReview,
            phase: { path: '/gather/phase' },
            image: { path: '/gather/image' },
            segmentation: { path: '/gather/segmentation' },
            classification: { path: '/gather/classification' },
            result: { path: '/gather/result' },
            outputReview: { path: '/gather/outputReview' },
            error: { path: '/gather/error' },
            statePath: '/gather',
          },
        ],
      },
    },
    {
      version: 'v0.9',
      updateDataModel: {
        surfaceId: 'segment-and-measure',
        path: '/gather',
        value: {
          phase: 'capture',
          image: null,
          segmentation: null,
          classification: null,
          result: null,
          outputReview: SEGMENT_AND_MEASURE_OUTPUT_REVIEW,
          error: null,
        },
      },
    },
  ]),
  hostActions: Object.freeze([
    GATHER_ACTION_IDS.capture,
    GATHER_ACTION_IDS.segment,
    GATHER_ACTION_IDS.classify,
    GATHER_ACTION_IDS.accept,
    GATHER_ACTION_IDS.retake,
  ]),
});
