import { GATHER_ACTION_IDS, GATHER_CATALOG_ID, GATHER_COMPONENT_IDS } from './identifiers.js';

const SEGMENT_AND_MEASURE_OUTPUT_REVIEW = Object.freeze({
  title: 'Result accepted',
  description: 'Analysis is ready to include in this observation.',
  sections: [
    { id: 'measurements', label: 'Measurements', order: 1 },
    { id: 'classification', label: 'Classification', order: 2 },
    { id: 'assets', label: 'Assets', order: 3 },
  ],
  fields: [
    {
      path: 'measurements.area.value',
      label: 'Area',
      format: 'quantity',
      unitPath: 'measurements.area.unit',
      section: 'measurements',
      decimals: 2,
      order: 1,
    },
    {
      path: 'measurements.perimeter.value',
      label: 'Perimeter',
      format: 'quantity',
      unitPath: 'measurements.perimeter.unit',
      section: 'measurements',
      decimals: 2,
      order: 2,
    },
    {
      path: 'measurements.boundingBox.width',
      label: 'Bounds width',
      format: 'quantity',
      unitPath: 'measurements.boundingBox.unit',
      section: 'measurements',
      decimals: 2,
      order: 3,
    },
    {
      path: 'measurements.boundingBox.height',
      label: 'Bounds height',
      format: 'quantity',
      unitPath: 'measurements.boundingBox.unit',
      section: 'measurements',
      decimals: 2,
      order: 4,
    },
    {
      path: 'measurements.sharpness.score',
      label: 'Sharpness',
      format: 'number',
      section: 'measurements',
      decimals: 2,
      order: 5,
    },
    {
      path: 'classification.ranked',
      label: 'Top labels',
      format: 'array',
      section: 'classification',
      order: 1,
      maxItems: 3,
      itemLabelPath: 'label',
      itemValuePath: 'score',
      itemValueFormat: 'percentage',
      itemValueScale: 'fraction',
      itemValueDecimals: 1,
      emptyText: 'Classification not run',
    },
    {
      path: 'segmentation.model.id',
      label: 'Segmentation model',
      format: 'string',
      section: 'assets',
      order: 1,
      emptyText: 'Segmentation completed',
    },
    {
      path: 'image',
      label: 'Captured image',
      format: 'asset',
      section: 'assets',
      order: 2,
      emptyText: 'Image summary unavailable',
    },
    {
      path: 'segmentation.mask',
      label: 'Mask asset',
      format: 'asset',
      section: 'assets',
      order: 3,
      emptyText: 'Mask summary unavailable',
    },
  ],
});

export const SEGMENT_AND_MEASURE_INSTRUMENT = Object.freeze({
  id: 'gather.segment-and-measure',
  revision: '0.1.0',
  catalogId: GATHER_CATALOG_ID,
  surfaceId: 'segment-and-measure',
  messages: Object.freeze([
    {
      version: 'v0.9',
      createSurface: {
        surfaceId: 'segment-and-measure',
        catalogId: GATHER_CATALOG_ID,
        sendDataModel: true,
      },
    },
    {
      version: 'v0.9',
      updateComponents: {
        surfaceId: 'segment-and-measure',
        components: [
          {
            id: 'root',
            component: 'Column',
            children: ['title', 'subtitle', 'capture', 'processing', 'error', 'reviewMaskPhase', 'acceptedPhase'],
          },
          { id: 'title', component: 'Text', text: 'Segment & Measure', variant: 'h2' },
          { id: 'subtitle', component: 'Text', text: 'Generic image measurements', variant: 'caption' },
          {
            id: 'capture',
            component: GATHER_COMPONENT_IDS.capture,
            phase: { path: '/gather/phase' },
            statePath: '/gather',
          },
          {
            id: 'processing',
            component: GATHER_COMPONENT_IDS.processingView,
            phase: { path: '/gather/phase' },
            image: { path: '/gather/image' },
          },
          {
            id: 'error',
            component: GATHER_COMPONENT_IDS.instrumentError,
            phase: { path: '/gather/phase' },
            error: { path: '/gather/error' },
            statePath: '/gather',
          },
          {
            id: 'reviewMaskPhase',
            component: GATHER_COMPONENT_IDS.phaseView,
            phase: { path: '/gather/phase' },
            when: ['review-mask'],
            child: 'reviewMaskContent',
          },
          {
            id: 'reviewMaskContent',
            component: 'Column',
            children: ['reviewMaskTitle', 'reviewMaskBody', 'imageOverlay', 'acceptMaskButton', 'retakeMaskButton'],
          },
          { id: 'reviewMaskTitle', component: 'Text', text: 'Review segmentation', variant: 'h3' },
          {
            id: 'reviewMaskBody',
            component: 'Text',
            text: 'The overlay is the proposed specimen mask. Confirm that it follows the specimen edge.',
            variant: 'caption',
          },
          {
            id: 'imageOverlay',
            component: GATHER_COMPONENT_IDS.imageOverlay,
            image: { path: '/gather/image' },
            segmentation: { path: '/gather/segmentation' },
          },
          {
            id: 'acceptMaskButton',
            component: 'Button',
            variant: 'primary',
            child: 'acceptMaskButtonText',
            action: { event: { name: GATHER_ACTION_IDS.accept, context: { statePath: '/gather' } } },
          },
          { id: 'acceptMaskButtonText', component: 'Text', text: 'Accept Mask', variant: 'body' },
          {
            id: 'retakeMaskButton',
            component: 'Button',
            child: 'retakeMaskButtonText',
            action: { event: { name: GATHER_ACTION_IDS.retake, context: { statePath: '/gather' } } },
          },
          { id: 'retakeMaskButtonText', component: 'Text', text: 'Retake', variant: 'body' },
          {
            id: 'acceptedPhase',
            component: GATHER_COMPONENT_IDS.phaseView,
            phase: { path: '/gather/phase' },
            when: ['accepted'],
            child: 'acceptedContent',
          },
          {
            id: 'acceptedContent',
            component: 'Column',
            children: ['outputReview', 'acceptResultButton', 'retakeResultButton'],
          },
          {
            id: 'outputReview',
            component: GATHER_COMPONENT_IDS.outputReview,
            data: { path: '/gather/result' },
            display: { path: '/gather/outputReview' },
          },
          {
            id: 'acceptResultButton',
            component: 'Button',
            variant: 'primary',
            child: 'acceptResultButtonText',
            action: { event: { name: GATHER_ACTION_IDS.accept, context: { statePath: '/gather' } } },
          },
          { id: 'acceptResultButtonText', component: 'Text', text: 'Accept', variant: 'body' },
          {
            id: 'retakeResultButton',
            component: 'Button',
            child: 'retakeResultButtonText',
            action: { event: { name: GATHER_ACTION_IDS.retake, context: { statePath: '/gather' } } },
          },
          { id: 'retakeResultButtonText', component: 'Text', text: 'Retake', variant: 'body' },
        ],
      },
    },
    {
      version: 'v0.9',
      updateDataModel: {
        surfaceId: 'segment-and-measure',
        path: '/gather',
        value: {
          phase: 'capture',
          image: null,
          segmentation: null,
          classification: null,
          result: null,
          outputReview: SEGMENT_AND_MEASURE_OUTPUT_REVIEW,
          error: null,
        },
      },
    },
  ]),
  hostActions: Object.freeze([
    GATHER_ACTION_IDS.capture,
    GATHER_ACTION_IDS.segment,
    GATHER_ACTION_IDS.classify,
    GATHER_ACTION_IDS.accept,
    GATHER_ACTION_IDS.retake,
  ]),
});
