# .github/workflows/eas-build.yml

name: EAS Build

on:
  push:
    branches:
      - main
      - development
      - 'feature/**'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  eas-build:
    if: >-
      github.ref == 'refs/heads/main' ||
      github.ref == 'refs/heads/development' ||
      github.event_name == 'pull_request' ||
      (startsWith(github.ref, 'refs/heads/feature/') && contains(github.event.head_commit.message, '[build]'))

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Authenticate with EAS
        run: eas login --token ${{ secrets.EAS_TOKEN }}

      - name: Set build environment
        run: |
          if [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then
            echo "EAS_BUILD_PROFILE=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == 'refs/heads/development' ]]; then
            echo "EAS_BUILD_PROFILE=testing" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == 'pull_request' ]]; then
            echo "EAS_BUILD_PROFILE=testing" >> $GITHUB_ENV
          else
            echo "EAS_BUILD_PROFILE=development" >> $GITHUB_ENV

      - name: Run EAS Build
        run: eas build --platform all --profile $EAS_BUILD_PROFILE --non-interactive
