# .github/workflows/eas-build.yml

name: EAS Build

on:
  push:
    branches:
      - main
      - development
      - 'feature/**'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  determine-release-type:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.read-version.outputs.release-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Read version from package.json
        id: read-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Release version: $VERSION"
          echo "release-version=$VERSION" >> $GITHUB_OUTPUT

  eas-build:
    needs: determine-release-type
    if: >-
      github.ref == 'refs/heads/main' ||
      github.ref == 'refs/heads/development' ||
      github.event_name == 'pull_request' ||
      (startsWith(github.ref, 'refs/heads/feature/') && contains(github.event.head_commit.message, '[build]'))
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: yarn

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EAS_TOKEN }}  # <- Make sure this is set in your repo secrets

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Determine build profile
        run: |
          VERSION=${{ needs.determine-release-type.outputs.release-version }}
          echo "App version: $VERSION"

          if [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then
            if [[ "$VERSION" =~ ^[0-9]+\.0\.0$ || "$VERSION" =~ ^[0-9]+\.[0-9]+\.0$ ]]; then
              echo "EAS_BUILD_PROFILE=production" >> $GITHUB_ENV
              echo "RUN_BUILD=true" >> $GITHUB_ENV
            else
              echo "RUN_BUILD=false" >> $GITHUB_ENV
            fi
          elif [[ "${{ github.ref }}" == 'refs/heads/development' ]]; then
            echo "EAS_BUILD_PROFILE=testing" >> $GITHUB_ENV
            echo "RUN_BUILD=true" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == 'pull_request' ]]; then
            echo "EAS_BUILD_PROFILE=testing" >> $GITHUB_ENV
            echo "RUN_BUILD=true" >> $GITHUB_ENV
          else
            echo "EAS_BUILD_PROFILE=development" >> $GITHUB_ENV
            echo "RUN_BUILD=true" >> $GITHUB_ENV
          fi

      - name: Run EAS Build or Publish
        run: |
          if [[ "$RUN_BUILD" == "true" ]]; then
            echo "Triggering EAS build with profile: $EAS_BUILD_PROFILE"
            eas build --platform all --profile $EAS_BUILD_PROFILE --non-interactive
          else
            echo "Triggering OTA update to 'production' channel"
            COMMIT_MESSAGE=$(git log -1 --pretty=%B | head -n 1)
            eas update --channel production --message "${COMMIT_MESSAGE}" --non-interactive
          fi
